// SPDX-License-Identifier: MIT OR Apache-2.0
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;
pub const PREFIX: &str = "/rights-nobody-has-to-earn/";
pub const ORIGIN: &str = "https://dhilipsiva.dev";
pub const REPOSITORY: &str = "https://github.com/dhilipsiva/rights-nobody-has-to-earn";
/// Public downloads open on the hosted site from desktop, not its asset server.
pub fn public_url(path: impl AsRef<str>) -> String {
    #[cfg(feature = "desktop")]
    {
        format!("{ORIGIN}{}", path.as_ref())
    }
    #[cfg(not(feature = "desktop"))]
    {
        path.as_ref().into()
    }
}
#[derive(Clone, Deserialize, Serialize, PartialEq)]
pub struct Section {
    pub id: String,
    pub title: String,
    pub level: u8,
}
#[derive(Clone, Deserialize, Serialize, PartialEq)]
pub struct Page {
    pub stem: String,
    pub title: String,
    pub label: String,
    pub number: Option<u8>,
    pub part: Option<String>,
    pub order: usize,
    pub path: String,
    pub canonical: String,
    pub source: String,
    pub description: String,
    /// The one-line summary from the annotated contents, empty where none.
    #[serde(default)]
    pub summary: String,
    pub html: String,
    pub text: String,
    pub markdown: String,
    pub sections: Vec<Section>,
    pub previous: Option<String>,
    pub next: Option<String>,
}
#[derive(Deserialize)]
pub struct Book {
    pub title: String,
    pub author: String,
    pub license: String,
    pub word_count: usize,
    pub pages: Vec<Page>,
}
#[derive(Clone, Deserialize)]
pub struct Question {
    pub id: String,
    pub text: String,
    pub chapters: Vec<u8>,
    pub part: u8,
}
#[derive(Clone, Deserialize)]
pub struct Term {
    pub name: String,
    pub definition: String,
    pub chapter: Option<u8>,
}
#[derive(Deserialize)]
pub struct Companion {
    pub questions: Vec<Question>,
    pub terms: Vec<Term>,
}
#[derive(Clone, Deserialize)]
pub struct Comparison {
    pub constitution: String,
    pub provision: String,
    pub url: String,
    pub quote: String,
}
#[derive(Clone, Deserialize)]
pub struct Article {
    pub number: u8,
    pub part: usize,
    pub title: String,
    pub core: String,
    pub text: Vec<String>,
    pub families: Vec<String>,
    pub records: Vec<String>,
    pub pins: Vec<String>,
    pub chapters: Vec<u8>,
    pub formal: String,
    pub gap: Option<String>,
    pub lineage: Vec<Comparison>,
    pub novelty: String,
}
#[derive(Deserialize)]
pub struct Articles {
    pub title: String,
    pub note: String,
    pub parts: Vec<String>,
    pub articles: Vec<Article>,
}
#[derive(Clone, Deserialize)]
pub struct Link {
    pub label: String,
    pub path: String,
}
#[derive(Clone, Deserialize)]
pub struct Moved {
    pub chapter: u8,
    pub title: String,
    pub text: String,
    pub links: Vec<Link>,
}
#[derive(Clone, Deserialize)]
pub struct GuidedStep {
    pub text: String,
    pub query: String,
    pub verdict: String,
}
#[derive(Clone, Deserialize)]
pub struct Guided {
    pub fork: String,
    pub pins: String,
    pub note: String,
    pub steps: Vec<GuidedStep>,
}
#[derive(Clone, Deserialize)]
pub struct Explainer {
    pub fork: String,
    pub joint: String,
    pub text: Vec<String>,
}
/// The design in ten minutes: sentences of the plain-language articles,
/// each with the article that states it and the chapter that argues it.
#[derive(Deserialize)]
pub struct Design {
    pub title: String,
    pub note: String,
    pub sections: Vec<DesignSection>,
}
#[derive(Deserialize)]
pub struct DesignSection {
    pub heading: String,
    /// The chapter a section's own headings come from, with a note saying so.
    #[serde(default)]
    pub chapter: Option<u8>,
    #[serde(default)]
    pub note: Option<String>,
    pub groups: Vec<DesignGroup>,
}
#[derive(Deserialize)]
pub struct DesignGroup {
    #[serde(default)]
    pub heading: Option<String>,
    pub lines: Vec<DesignLine>,
}
#[derive(Deserialize)]
pub struct DesignLine {
    pub text: String,
    pub article: u8,
    pub chapter: u8,
}
/// What would change each choice and who bears its cost, quoted from the
/// chapters' argument sections by `tools/reconsider_index.py`.
#[derive(Deserialize)]
pub struct Reconsider {
    pub title: String,
    pub note: String,
    pub conditions: Vec<ReconsiderGroup>,
    pub costs: Vec<ReconsiderGroup>,
}
#[derive(Deserialize)]
pub struct ReconsiderGroup {
    pub id: String,
    pub title: String,
    pub entries: Vec<ReconsiderEntry>,
}
#[derive(Deserialize)]
pub struct ReconsiderEntry {
    pub chapter: u8,
    pub title: String,
    pub file: String,
    pub heading: String,
    pub text: String,
}
/// What was checked and what is left open, generated by
/// `tools/assurance_pages.py` from the records that carry each.
#[derive(Deserialize)]
pub struct Assurance {
    pub engine: EngineCheck,
    pub limits: Limits,
}
#[derive(Deserialize)]
pub struct EngineCheck {
    pub clingo: String,
    pub statements: u32,
    pub queries: u32,
    pub differences: u32,
    pub groups: Vec<EngineGroup>,
    pub keeps: Vec<String>,
    pub leaves_out: Vec<String>,
    pub limit: String,
    pub method_section: String,
    pub cases: Vec<EngineCase>,
}
#[derive(Deserialize)]
pub struct EngineGroup {
    pub name: String,
    pub cases: u32,
}
#[derive(Deserialize)]
pub struct EngineCase {
    pub id: String,
    pub queries: u32,
    pub differences: u32,
}
#[derive(Deserialize)]
pub struct Limits {
    pub findings: Vec<OpenFinding>,
    pub defects: Vec<DeclaredDefect>,
    pub chapters: Vec<ChapterLimit>,
}
#[derive(Deserialize)]
pub struct OpenFinding {
    pub lens: String,
    pub finding: String,
    pub withholds: String,
    pub disposition: String,
}
#[derive(Deserialize)]
pub struct DeclaredDefect {
    pub file: String,
    pub line: u32,
    pub reason: String,
}
#[derive(Deserialize)]
pub struct ChapterLimit {
    pub number: u8,
    pub title: String,
    pub file: String,
    pub paragraphs: Vec<String>,
}
#[derive(Deserialize)]
pub struct Start {
    pub title: String,
    pub panel: Vec<String>,
    pub guided: Guided,
    pub explainer: Explainer,
}
#[derive(Deserialize)]
pub struct ChapterCases {
    pub title: String,
    pub note: String,
    pub moved: Vec<Moved>,
}
/// A repository link for a file, a directory or a heading in a Markdown file.
pub fn repository_url(path: &str) -> String {
    let (file, anchor) = path.split_once('#').unwrap_or((path, ""));
    let kind = if file
        .rsplit('/')
        .next()
        .is_some_and(|name| name.contains('.'))
    {
        "blob"
    } else {
        "tree"
    };
    let anchor = if anchor.is_empty() {
        String::new()
    } else {
        format!("#{anchor}")
    };
    format!("{REPOSITORY}/{kind}/main/{file}{anchor}")
}
#[derive(Clone, Deserialize, Serialize, PartialEq)]
pub struct Verdict {
    pub query: String,
    pub status: String,
    pub detail: Option<String>,
}
#[derive(Clone, Deserialize, Serialize, PartialEq)]
pub struct Outcome {
    pub id: String,
    pub counterfactual: Option<String>,
    pub complete: bool,
    pub verdicts: Vec<Verdict>,
}
#[derive(Clone, Deserialize, Serialize, PartialEq)]
pub struct Scenario {
    pub id: String,
    pub counterfactual: Option<String>,
    pub record: Vec<String>,
    pub queries: Vec<String>,
    pub sources: Vec<Source>,
}
#[derive(Clone, Deserialize, Serialize, PartialEq)]
pub struct Source {
    pub path: String,
    pub through_line: Option<usize>,
}
#[derive(Deserialize)]
pub struct Cases {
    pub engine_revision: String,
    pub cases: Vec<Scenario>,
}
pub fn book() -> &'static Book {
    static B: OnceLock<Book> = OnceLock::new();
    B.get_or_init(|| {
        serde_json::from_str(include_str!("../generated/book.json")).expect("assembled book")
    })
}
pub fn companion() -> &'static Companion {
    static C: OnceLock<Companion> = OnceLock::new();
    C.get_or_init(|| {
        serde_json::from_str(include_str!("../companion.json")).expect("companion copy")
    })
}
pub fn articles() -> &'static Articles {
    static A: OnceLock<Articles> = OnceLock::new();
    A.get_or_init(|| {
        serde_json::from_str(include_str!("../articles.json")).expect("plain-language articles")
    })
}
pub fn chapter_cases() -> &'static ChapterCases {
    static C: OnceLock<ChapterCases> = OnceLock::new();
    C.get_or_init(|| {
        serde_json::from_str(include_str!("../chapter-cases.json")).expect("chapter cases")
    })
}
/// A count with thousands separated by commas, as the book writes them.
pub fn thousands(n: u32) -> String {
    let digits = n.to_string();
    let mut out = String::new();
    for (i, c) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    out
}
pub fn design() -> &'static Design {
    static D: OnceLock<Design> = OnceLock::new();
    D.get_or_init(|| {
        serde_json::from_str(include_str!("../design.json")).expect("the design summary")
    })
}
pub fn reconsider() -> &'static Reconsider {
    static R: OnceLock<Reconsider> = OnceLock::new();
    R.get_or_init(|| {
        serde_json::from_str(include_str!("../reconsider.json")).expect("conditions and costs")
    })
}
pub fn assurance() -> &'static Assurance {
    static A: OnceLock<Assurance> = OnceLock::new();
    A.get_or_init(|| {
        serde_json::from_str(include_str!("../assurance.json")).expect("checks and limits")
    })
}
pub fn start() -> &'static Start {
    static S: OnceLock<Start> = OnceLock::new();
    S.get_or_init(|| serde_json::from_str(include_str!("../start.json")).expect("start copy"))
}
pub fn cases() -> &'static Cases {
    static C: OnceLock<Cases> = OnceLock::new();
    C.get_or_init(|| {
        serde_json::from_str(include_str!("../generated/cases.json")).expect("input-only scenarios")
    })
}
pub fn chapter(number: u8) -> &'static Page {
    book()
        .pages
        .iter()
        .find(|p| p.number == Some(number))
        .expect("chapter")
}
pub fn page(stem: &str) -> Option<&'static Page> {
    book().pages.iter().find(|p| p.stem == stem)
}
pub fn question_path(q: &Question) -> String {
    chapter(q.chapters[0]).path.clone()
}
pub fn route_title(path: &str) -> String {
    if let Some(p) = book().pages.iter().find(|p| p.path == path) {
        return p.label.clone();
    }
    match path.strip_prefix(PREFIX).unwrap_or("404") {
        "" => "Pick a person. Walk their forks.",
        "map/" => "Reader’s map",
        "walkthrough/food-delivery/" => "Does a receipt prove I was fed?",
        "about/" => "About the book and companion",
        "read/" => "Read Book 1",
        "search/" => "Search Book 1",
        "constitution/" => "The constitution in plain language",
        "cases/" => "Run the chapters",
        "start/" => "Start here",
        "second-engine/" => "The second engine",
        "limits/" => "Current limits",
        "design/" => "The design in ten minutes",
        "reconsider/" => "What would change a choice",
        _ => "Page not found",
    }
    .into()
}
pub fn routes() -> Vec<String> {
    [
        "",
        "start/",
        "read/",
        "search/",
        "constitution/",
        "cases/",
        "second-engine/",
        "limits/",
        "design/",
        "reconsider/",
    ]
    .iter()
    .map(|p| format!("{PREFIX}{p}"))
    .chain(book().pages.iter().map(|p| p.path.clone()))
    .collect()
}
pub fn search(query: &str) -> Vec<(&'static Page, String)> {
    let needle = query.trim().to_lowercase();
    if needle.is_empty() {
        return vec![];
    }
    let words: Vec<_> = needle.split_whitespace().collect();
    book()
        .pages
        .iter()
        .filter_map(|page| {
            let lower = page.text.to_lowercase();
            if !words.iter().all(|word| lower.contains(word)) {
                return None;
            }
            // Map byte positions through characters, so Tamil and case expansion never
            // become invalid UTF-8 boundaries in a snippet.
            let chars: Vec<char> = page.text.chars().collect();
            let first = lower.find(words[0]).unwrap_or(0);
            let position = lower[..first].chars().count().min(chars.len());
            let start = position.saturating_sub(70);
            let end = (position + 230).min(chars.len());
            Some((
                page,
                format!(
                    "{}{}{}",
                    if start > 0 { "…" } else { "" },
                    chars[start..end].iter().collect::<String>(),
                    if end < chars.len() { "…" } else { "" }
                ),
            ))
        })
        .collect()
}
#[cfg(test)]
mod assurance_tests {
    use super::*;
    #[test]
    fn counts_are_written_with_thousands_separated() {
        assert_eq!(thousands(9), "9");
        assert_eq!(thousands(129), "129");
        assert_eq!(thousands(1673), "1,673");
        assert_eq!(thousands(90187), "90,187");
        assert_eq!(thousands(1234567), "1,234,567");
    }
    #[test]
    fn the_generated_pages_load() {
        let a = assurance();
        assert_eq!(
            a.engine.queries,
            a.engine.cases.iter().map(|c| c.queries).sum::<u32>()
        );
        assert!(!a.limits.chapters.is_empty());
    }
    #[test]
    fn every_reconsider_entry_names_a_chapter_that_exists() {
        let r = reconsider();
        for group in r.conditions.iter().chain(r.costs.iter()) {
            assert!(!group.entries.is_empty(), "{}", group.id);
            for entry in &group.entries {
                assert_eq!(chapter(entry.chapter).number, Some(entry.chapter));
            }
        }
    }
    #[test]
    fn the_design_summary_links_articles_and_chapters_that_exist() {
        let d = design();
        let lines: Vec<_> = d
            .sections
            .iter()
            .flat_map(|s| s.groups.iter())
            .flat_map(|g| g.lines.iter())
            .collect();
        assert!(!lines.is_empty());
        for line in lines {
            assert!(
                articles().articles.iter().any(|a| a.number == line.article),
                "Article {}",
                line.article
            );
            assert_eq!(chapter(line.chapter).number, Some(line.chapter));
        }
    }
}
