// SPDX-License-Identifier: MIT OR Apache-2.0

//! The reader-experience coverage ledger: one record per derived-chapter
//! section and per substantive Part V passage, projected into a report.
//!
//! It classifies what the reader actually meets — which domain, which rule
//! family, whether the passage shows ordinary operation or a protection, what
//! the person in it is doing, and how it ends. Its value is the gaps it
//! exposes, so the report prints those first and does not average them away.

use super::Export;
use crate::{cli::Error, context::Context};
use serde::Deserialize;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

const SOURCE: &str = "new-book-plans/reader-coverage-source.json";
const REPORT: &str = "new-book-plans/reader-coverage.md";

/// Trajectories that show the design under strain rather than working.
const TROUBLE: [&str; 4] = ["contested", "fails", "continuity-remedy", "unresolved"];

#[derive(Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct Record {
    pub(crate) id: String,
    pub(crate) chapter: String,
    pub(crate) section: String,
    pub(crate) domain: String,
    pub(crate) family: String,
    pub(crate) function: String,
    pub(crate) setting: String,
    pub(crate) posture: String,
    pub(crate) trajectory: String,
    pub(crate) basis: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Source {
    records: Vec<Record>,
}

pub(crate) fn records(context: &Context) -> Result<Vec<Record>, Error> {
    let source: Source = serde_json::from_str(&context.read(SOURCE)?)?;
    Ok(source.records)
}

/// Every `## ` heading of a derived chapter and of Part V, in file order. The
/// opening note is one of the three exempt elements and is deliberately absent.
pub(crate) fn headings(context: &Context) -> Result<Vec<(String, String)>, Error> {
    let mut rows = Vec::new();
    let mut files: Vec<_> = std::fs::read_dir(context.path("book-1"))?
        .filter_map(Result::ok)
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| {
            name.ends_with(".md")
                && name.starts_with(|c: char| c.is_ascii_digit())
                && name != "00-opening-note.md"
        })
        .collect();
    files.sort();
    for name in files {
        let path = format!("book-1/{name}");
        for line in context.read(&path)?.lines() {
            if let Some(heading) = line.strip_prefix("## ") {
                rows.push((path.clone(), heading.trim().to_owned()));
            }
        }
    }
    Ok(rows)
}

fn validate(context: &Context, records: &[Record]) -> Result<(), Error> {
    let declared: Vec<(String, String)> = records
        .iter()
        .map(|record| (record.chapter.clone(), record.section.clone()))
        .collect();
    let present = headings(context)?;
    if declared != present {
        let missing: Vec<_> = present
            .iter()
            .filter(|row| !declared.contains(row))
            .take(4)
            .collect();
        let extra: Vec<_> = declared
            .iter()
            .filter(|row| !present.contains(row))
            .take(4)
            .collect();
        return Err(Error::new(format!(
            "the ledger and the book disagree. Unclassified passages: {missing:?}. \
             Records with no passage: {extra:?}"
        )));
    }
    let mut seen = BTreeSet::new();
    for record in records {
        if !seen.insert(&record.id) {
            return Err(Error::new(format!("duplicate record {}", record.id)));
        }
        if record.basis != "exempt-element" && !context.path(&record.basis).exists() {
            return Err(Error::new(format!(
                "{}: basis {} does not exist",
                record.id, record.basis
            )));
        }
        if !TROUBLE.contains(&record.trajectory.as_str()) && record.trajectory != "works" {
            return Err(Error::new(format!(
                "{}: unknown trajectory {}",
                record.id, record.trajectory
            )));
        }
    }
    Ok(())
}

pub(crate) fn coverage(records: &[Record]) -> BTreeMap<String, (usize, usize)> {
    let mut rows: BTreeMap<String, (usize, usize)> = BTreeMap::new();
    for record in records {
        let entry = rows.entry(record.domain.clone()).or_default();
        if record.trajectory == "works" {
            entry.0 += 1;
        } else {
            entry.1 += 1;
        }
    }
    rows
}

fn render(records: &[Record]) -> String {
    let mut out = String::from(
        "<!-- SPDX-License-Identifier: CC-BY-4.0 -->\n\n\
         # Reader-experience coverage\n\n\
         Generated by `./generate.sh reader-coverage` from\n\
         `reader-coverage-source.json`. One row per derived-chapter section and\n\
         per Part V passage. The opening note is an exempt element and is not\n\
         classified here.\n\n\
         This is a map of what a reader meets, not a claim about whether they\n\
         understand it. No reader has been asked anything; R6 is unbuilt, and\n\
         nothing here is reader evidence.\n\n\
         ## Where a domain is thin\n\n\
         A domain needs ordinary operation **and** a credible failure, abuse or\n\
         boundary. The rows below have one and not the other, and naming them is\n\
         what this ledger is for — the portfolio rebalance and the chapter-pattern\n\
         items consume this table.\n\n\
         | Domain | Ordinary | Under strain | Missing |\n| --- | ---: | ---: | --- |\n",
    );
    let rows = coverage(records);
    for (domain, (works, trouble)) in &rows {
        let missing = match (works, trouble) {
            (0, _) => "ordinary operation",
            (_, 0) => "a failure, abuse or boundary",
            _ => continue,
        };
        let _ = writeln!(out, "| {domain} | {works} | {trouble} | {missing} |");
    }
    out.push_str(
        "\n## Every domain\n\n| Domain | Ordinary | Under strain |\n| --- | ---: | ---: |\n",
    );
    for (domain, (works, trouble)) in &rows {
        let _ = writeln!(out, "| {domain} | {works} | {trouble} |");
    }
    out.push_str("\n## Every passage\n\n| ID | Chapter | Section | Domain | Family | Function | Setting | Posture | Trajectory | Basis |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n");
    for record in records {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | `{}` |",
            record.id,
            record.chapter.trim_start_matches("book-1/"),
            record.section,
            record.domain,
            record.family,
            record.function,
            record.setting,
            record.posture,
            record.trajectory,
            record.basis
        );
    }
    out
}

pub(crate) fn generate(context: &Context, _export: &mut Export) -> Result<(), Error> {
    let records = records(context)?;
    validate(context, &records)?;
    std::fs::write(context.path(REPORT), render(&records))?;
    println!("reader coverage: {} passages classified", records.len());
    Ok(())
}

#[cfg(test)]
#[path = "reader_coverage_tests.rs"]
mod tests;
