#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate Book 1's works cited from the notes of its reading inputs.

Every work a note cites becomes one entry, in alphabetical order, with the
places that cite it. The citation is taken as written in the note, up to the
note's commentary; a note that only points back to the previous one ("The same
judgment ...") adds its place to that work. `--check` fails if the file is out
of date, so an edited note cannot leave the list behind.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
import unicodedata

ROOT = Path(__file__).resolve().parent.parent
BOOK = ROOT / "book-1"
OUTPUT = BOOK / "bibliography.md"
YEAR = re.compile(r"\b(1[5-9]\d\d|20\d\d)\b")
LINK = re.compile(r"\[([^\]]*)\]\(([^)\s]+(?:\([^)\s]*\))?[^)\s]*)\)")

HEADER = """<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Generated by tools/bibliography.py from the notes of the reading inputs; edit the notes, not this file. -->

# Works Cited

Every work the book's notes cite, in alphabetical order, with the places that
cite it. The notes themselves give the pinpoint, and say what was read where
only an abstract or a description could be checked; the figures the arguments
use are also recorded, with their sources, in the book's evidence registry.

"""


def inputs() -> list[tuple[str, str]]:
    """Each reading input with the name of the place it occupies."""
    manifest = json.loads((BOOK / "contents.json").read_text(encoding="utf-8"))
    rows = [(name, "the epigraph" if name == "epigraph.md" else "the opening note")
            for name in manifest["front"]]
    for index, part in enumerate(manifest["parts"], 1):
        opener = part.get("opener", {})
        roman = ["I", "II", "III", "IV", "V"][index - 1]
        if opener.get("status") == "landed":
            rows.append((opener["file"], f"Part {roman}'s opening case"))
        rows += [(c["file"], f"Chapter {c['number']}") for c in part["chapters"] if c["status"] == "landed"]
    rows += [(name, "the method" if name == "method.md" else name) for name in manifest["back"]
             if name not in {"bibliography.md", "index.md"}]
    return rows


def notes(text: str) -> list[str]:
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    found = []
    for match in re.finditer(r"^\[\^[^\]]+\]:(.*(?:\n(?:    .*|))*)", text, re.M):
        found.append(" ".join(match.group(1).split()))
    return found


def top_level_split(text: str, separator: str) -> list[str]:
    """Split outside brackets, parentheses and quotation marks."""
    parts, depth, start, index = [], 0, 0, 0
    while index < len(text):
        char = text[index]
        if char in "([“":
            depth += 1
        elif char in ")]”" and depth:
            depth -= 1
        elif depth == 0 and text.startswith(separator, index):
            parts.append(text[start:index])
            start = index + len(separator)
            index = start
            continue
        index += 1
    parts.append(text[start:])
    return [p.strip() for p in parts if p.strip()]


ABBREVIATIONS = {
    "p", "pp", "s", "ss", "para", "paras", "no", "nos", "vol", "vols", "ch", "chs", "art", "arts",
    "trans", "ed", "eds", "supp", "u.s", "s.c.r", "c.j", "v", "st", "al", "doc", "e.g", "i.e", "cf",
    "co", "inc", "ltd", "dr", "jr", "n", "fn", "sec", "cl", "bgbl", "op", "rev", "repr", "ibid", "c",
    "cj", "jj", "mr", "mrs", "ms", "prof", "sr", "nr", "fig", "figs", "approx", "ca", "ff", "l",
}


def sentences(text: str) -> list[str]:
    """Split into sentences, never after an abbreviation or an initial."""
    parts, depth, start = [], 0, 0
    for index, char in enumerate(text):
        if char in "([“":
            depth += 1
        elif char in ")]”" and depth:
            depth -= 1
        elif (char == "." and depth == 0 and text[index + 1:index + 2] == " "
              and text[index + 2:index + 3].isupper()):
            word = re.search(r"([\w.]+)$", text[start:index])
            word = word.group(1).lower() if word else ""
            if word in ABBREVIATIONS or re.fullmatch(r"[a-z]", word) or re.fullmatch(r"(?:[a-z]\.)+[a-z]", word):
                continue
            parts.append(text[start:index + 1].strip())
            start = index + 2
    parts.append(text[start:].strip())
    return [p for p in parts if p]


COMMENTARY = re.compile(r"^(The (argument|abstract|full text|book|article|figures?|text|report|resolution|"
                        r"judgment turns|Court (accepted|did|found|held|declined))|It |This |These |Stated |Read |"
                        r"Quoted |Checked |Only )", re.I)


def citation(note: str) -> str:
    """The note up to its commentary: the first sentence that cites something."""
    sentences_ = sentences(note)
    kept = []
    for sentence in sentences_:
        kept.append(sentence)
        joined = ". ".join(kept)
        if YEAR.search(joined) or LINK.search(joined):
            break
    text = " ".join(kept).rstrip(".")
    return text + "."


def continues(note: str) -> bool:
    return bool(re.match(r"(The same|Ibid|Id\.|See also the same)\b", note))


INSTITUTIONAL = re.compile(
    r"\b(Court|Assembly|Nations|Council|Commission|Committee|Act|Law|Constitution|Convention|Office|Bank|"
    r"Agency|Ministry|Department|Government|Republic|Union|Organi[sz]ation|Supreme|Federal|International|"
    r"National|University|Press|Institute|Board|Tribunal|Parliament|Senate|Secretary|General|Comptroller|"
    r"Treasury|Project|Foundation|Group|Centre|Center|Service|Society|Network|Reporting|Regulation|Basic|"
    r"Treaty|Declaration|Principles|Rules|Bundesverfassungsgericht|Corte|Hoge|Conseil|Tweede|Kamer|OECD|"
    r"MONDRAGON|Mondragon|Auroville|Kerala|Principle|Code|Charter|Protocol|Statute|Report|Review|Survey|"
    r"Zealand|Africa|Kingdom|States|Canada|India|Germany|Swiss|Chile|Hungary|Wales|Netherlands)\b")


def key(work: str) -> str:
    """Sort a personal author by the first author's surname, anything else as written."""
    titled = work.lstrip().startswith(("*", "[*", '"', "“", "[“", '["'))
    plain = LINK.sub(lambda m: m.group(1), work)
    plain = re.sub(r"[*_“”\"'\[\]]", "", plain).strip()
    head = re.sub(r"\s*\([^)]*\)", "", plain.split(",")[0]).replace(" et al.", "")
    first = re.split(r" and ", head)[0].split()
    person = (not titled and 2 <= len(first) <= 4 and not INSTITUTIONAL.search(head) and not YEAR.search(head)
              and all(re.match(r"^[A-ZÀ-Ž][\w.\-’']*$", w) for w in first) and "," in plain)
    surname = first[-1] if person else ""
    if person and len(first) >= 3 and first[-2] in {"Van", "Von", "De", "Del", "Della", "Di", "Le", "La", "Du"}:
        surname = f"{first[-2]} {first[-1]}"
    possessive = re.match(r"([A-ZÀ-Ž]\w+) ([A-ZÀ-Ž][\w\-]+)['’]s ", plain)
    reporter = re.search(r"\(([A-ZÀ-Ž]\w+) ([A-ZÀ-Ž][\w\-]+), \d", plain)
    if not person and possessive and not INSTITUTIONAL.search(possessive.group(0)):
        surname = possessive.group(2)
    elif not person and reporter:
        surname = reporter.group(2)
    base = f"{surname} {plain}" if surname else plain
    base = unicodedata.normalize("NFKD", base).encode("ascii", "ignore").decode().lower()
    return re.sub(r"^(the|a|an) ", "", base)


def places_text(places: list[str]) -> str:
    """'Chapters 3 and 29; the method' from the places a work is cited."""
    numbers = sorted(int(p.split()[1]) for p in places if re.fullmatch(r"Chapter \d+", p))
    others = [p for p in places if not re.fullmatch(r"Chapter \d+", p)]
    parts = []
    if numbers:
        listed = [str(n) for n in numbers]
        words = listed[0] if len(listed) == 1 else ", ".join(listed[:-1]) + " and " + listed[-1]
        parts.append(("Chapter " if len(listed) == 1 else "Chapters ") + words)
    parts += others
    return "; ".join(parts)


def author(work: str) -> str:
    """The personal author a work begins with, or nothing."""
    head = work.split(",")[0]
    if work.startswith(("*", '"', "“", "[")) or INSTITUTIONAL.search(head) or YEAR.search(head):
        return ""
    words = re.sub(r" et al\.$", "", head).split()
    if 2 <= len(words) <= 4 and all(re.match(r"^[A-ZÀ-Ž][\w.\-’']*$", w) for w in words):
        return head
    return ""


# Where a later sentence of a note begins to cite a work: an author and a
# title, an italic case name, or a link to a legal provision.
WORK_START = re.compile(
    r"(?:(?:[A-ZÀ-Ž][\w.'’\-]*\.? ){0,3}[A-ZÀ-Ž][\w'’\-]+(?: et al\.)?"
    r"(?:(?:, | and )(?:[A-ZÀ-Ž][\w.'’\-]*\.? ){0,3}[A-ZÀ-Ž][\w'’\-]+)*, \[?[*\"“])"
    r"|\*[A-Z][^*]*? v\.? [^*]+\*"
    r"|\[(?:Article|Section|Art\.) [^\]]*\]\([^)]+\)")
# Commentary that follows a citation inside its sentence.
TRAILING = re.compile(r",? (?:describes|dates|records|quotes|reports|found|finds|shows|states|notes|explains)\b.*$"
                      r"|: (?:his|her|their|its|the|a|an)\b.*$")


def trim(work: str) -> str:
    """Drop commentary a sentence adds after the citation itself."""
    work = re.sub(r": (?:his|her|their|its|the|a|an)\b.*$", "", work)
    year = YEAR.search(work)
    start = year.end() if year else 0
    match = TRAILING.search(work, start)
    return work[:match.start()] if match else work


def cited_parts(note: str) -> list[str]:
    """The citation text of a note: its first citing sentence, then any later
    sentence from the point where it begins to cite a work."""
    parts = [citation(note).rstrip(".")]
    rest = note[len(citation(note).rstrip(".")):]
    for sentence in sentences(rest.lstrip(". ")):
        found = WORK_START.search(sentence)
        if found and (YEAR.search(sentence[found.start():]) or LINK.search(sentence[found.start():])):
            parts.append(sentence[found.start():].rstrip("."))
    return parts


def note_works(note: str) -> list[str]:
    """The works one note cites, each with its further locators joined to it."""
    merged: list[str] = []
    segments = [(index == 0 and n > 0, w) for n, part in enumerate(cited_parts(note))
                for index, w in enumerate(top_level_split(trim(part), "; "))]
    for fresh, work in segments:
        work = re.sub(r"^(and |see |also )", "", work).strip().rstrip(".,")
        # A further locator for the same work ("2006 web edition, ch. 2A",
        # "[author copy](...)", "the lecture version ...") stays with it.
        further = (re.match(r"^[0-9]", work) or re.match(r"^\[[a-z]", work)
                   or (re.match(r"^[a-z]", work) and not re.match(r"^the [A-Z]", work))
                   or re.fullmatch(r"\[[^*“\"\]][^\]]*\]\([^)]*\)", work))
        if merged and further and not fresh:
            merged[-1] += "; " + work
            continue
        if (YEAR.search(work) or LINK.search(work)) and not COMMENTARY.match(work):
            # A second work by the same author in one note names no author;
            # give it the author of the work before it.
            case = re.match(r"\*[^*]* v\.? ", work)
            if merged and not case and work.startswith(("*", '"', "“", "[*", "[“")) and author(merged[-1]):
                work = f"{author(merged[-1])}, {work}"
            merged.append(work[0].upper() + work[1:])
    return [w + "." for w in merged]


def identity(work: str) -> str:
    """One work however its notes cite it: its first six words and first year,
    whatever link, subtitle or pinpoint follows."""
    plain = LINK.sub(lambda m: m.group(1), work)
    year = YEAR.search(plain)
    words = re.findall(r"\w+", plain.lower())
    return " ".join(words[:6]) + " " + year.group() if year else " ".join(words)


def works() -> list[tuple[str, list[str]]]:
    found: dict[str, tuple[str, list[str]]] = {}
    for name, place in inputs():
        last = None
        for note in notes((BOOK / name).read_text(encoding="utf-8")):
            if continues(note) and last:
                if place not in found[last][1]:
                    found[last][1].append(place)
                continue
            for work in note_works(note):
                ident = identity(work)
                found.setdefault(ident, (work, []))
                if place not in found[ident][1]:
                    found[ident][1].append(place)
                last = ident
    return sorted(found.values(), key=lambda item: key(item[0]))


def render() -> str:
    lines = [HEADER.rstrip("\n"), ""]
    letter = None
    for work, places in works():
        initial = key(work)[:1].upper()
        initial = initial if initial.isalpha() else "#"
        if initial != letter:
            lines += ([""] if letter else []) + [f"## {initial}", ""]
            letter = initial
        lines.append(f"- {work} Cited in {places_text(places)}.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("book-1/bibliography.md is out of date; run tools/bibliography.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"Wrote {len(works())} works to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
