#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate the alphabetical index at the end of `book-1/reference.md`.

Each entry is a term, body, person or documented case, with its principal
places in the reading sequence: chapter numbers, and the opening note, a Part's
opening case or the method by name. A term found in a few places lists them
all; a common one lists the places that use it most, up to eight. The terms are
listed here; the places are found in the text, so an edited chapter moves its
entries with it.
`--check` fails if the region is out of date.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
BOOK = ROOT / "book-1"
TARGET = BOOK / "reference.md"
BEGIN = "<!-- index:begin; generated by tools/book_index.py -->"
END = "<!-- index:end -->"

# (entry, patterns). A pattern is matched case-insensitively on word boundaries
# unless it is a name, which must match its capitals.
TERMS: list[tuple[str, list[str]]] = [
    ("accommodation", ["accommodation"]),
    ("adulthood", ["adulthood"]),
    ("advocate for the person", ["rights advocate"]),
    ("alternate, independent", ["independent alternate", "alternate reviewer"]),
    ("amendment", ["amendment", "amend"]),
    ("Animal Protection Advocate", ["Animal Protection Advocate", "Animal Advocate"]),
    ("animals", ["animal", "animals"]),
    ("answerability, public", ["answerability", "answerable"]),
    ("appeal", ["appeal", "appeals body"]),
    ("appointment", ["appointment", "appointments"]),
    ("asylum", ["asylum"]),
    ("authority to sign findings", ["authority to sign"]),
    ("ballot", ["ballot", "vote", "franchise"]),
    ("belief", ["belief"]),
    ("bodily safety", ["bodily safety"]),
    ("care", ["care"]),
    ("child with nobody", ["child with nobody", "one-line record"]),
    ("childcare-benefits affair", ["childcare-benefits", "childcare benefits", "Toeslagen"]),
    ("Civic President", ["Civic President"]),
    ("common tier", ["common tier"]),
    ("commons", ["commons"]),
    ("company", ["company"]),
    ("compensation", ["compensation"]),
    ("competence certificate", ["competence certificate", "certificate opens no door", "certifier"]),
    ("confinement", ["confinement", "confine", "confined"]),
    # Not Germany's Federal Constitutional Court.
    ("Constitutional Court", ["re:(?<!Federal )(?<!Germany's )Constitutional Court"]),
    ("continuity", ["continuity"]),
    ("contradiction check", ["contradiction"]),
    ("contribution", ["contribution"]),
    ("correction", ["correction"]),
    ("credibility finding", ["credibility finding", "credibility findings"]),
    ("custody", ["custody"]),
    ("custody authorisation", ["custody authorisation"]),
    ("delivery", ["delivery", "delivered"]),
    ("democratic corridor", ["democratic corridor"]),
    ("disclosure", ["disclosure", "disclosures"]),
    ("discrimination", ["discrimination"]),
    ("ecology", ["ecological", "river"]),
    ("emergency", ["emergency", "emergencies"]),
    ("entitlement", ["entitlement", "entitlements"]),
    ("equality", ["equality", "equal treatment"]),
    ("eviction", ["eviction"]),
    ("Executive Council", ["Executive Council"]),
    ("expression", ["expression"]),
    ("family", ["family", "families"]),
    ("first contact", ["first contact", "first-contact"]),
    ("floor", ["floor"]),
    ("food", ["food"]),
    ("free movement", ["free movement", "movement"]),
    ("future conditions", ["future conditions", "future generations"]),
    # The short form, but not the newspaper Chapter 19 cites.
    ("Future Conditions Guardian", ["Future Conditions Guardian", "re:the Guardian(?! reported)"]),
    ("harm", ["harm"]),
    ("initiation duty", ["initiation", "initiate"]),
    ("learning", ["learning", "teaching"]),
    ("locality", ["locality", "localities"]),
    ("lottery", ["lottery", "rotation"]),
    ("material security", ["material security"]),
    ("membership", ["membership"]),
    ("non-refoulement", ["non-refoulement"]),
    ("People's Assembly", ["People's Assembly", "Assembly"]),
    ("personhood", ["personhood"]),
    ("placement", ["placement"]),
    ("political home", ["political home"]),
    ("presence", ["presence"]),
    ("prisoner", ["prisoner", "prisoners"]),
    ("privacy", ["privacy", "private life"]),
    ("property", ["property", "ownership"]),
    ("protected core", ["protected core", "unamendable"]),
    ("public finance", ["public finance", "taxation", "tax", "budget"]),
    ("receipt", ["receipt", "receipts"]),
    ("recall", ["recall"]),
    ("recognition status", ["recognition"]),
    ("region", ["region", "regions"]),
    ("Regions Council", ["Regions Council"]),
    ("release", ["release"]),
    ("remedy", ["remedy", "remedies"]),
    ("requisition", ["requisition"]),
    ("residence", ["residence", "resident"]),
    ("restoration", ["restoration", "restorative"]),
    ("scarcity", ["scarcity", "shortage"]),
    ("search", ["search order", "searches", "a search"]),
    ("secure placement", ["secure placement", "secure place"]),
    ("severity", ["severity", "severe"]),
    ("shelter", ["shelter"]),
    ("shield", ["shield"]),
    ("signing restriction", ["signing restriction", "restriction on signing", "restricted signer", "restricts only a signature", "restricts one act", "bears the restriction"]),
    ("single-actor route", ["single actor", "one authorised actor"]),
    ("standing", ["standing"]),
    ("subsidiarity", ["subsidiarity"]),
    ("supplement", ["supplement"]),
    ("surveillance", ["surveillance", "watching"]),
    ("versions of the record", ["version in force", "versions of the record"]),
    ("wage", ["wage", "wages"]),
    ("witness", ["witness", "witnesses"]),
    ("work", ["work", "employment"]),
    # People the chapters follow, by name.
    ("Adam", ["Adam"]), ("Bela", ["Bela"]), ("Cira", ["Cira"]), ("Esa", ["Esa"]),
    ("Gia", ["Gia"]), ("Hano", ["Hano"]), ("Iris", ["Iris"]), ("Ivo", ["Ivo"]),
    ("Juno", ["Juno"]), ("Kel", ["Kel"]), ("Mael", ["Mael"]), ("Marisol", ["Marisol"]),
    ("Nell", ["Nell"]), ("Nia", ["Nia"]), ("Ruk", ["Ruk"]), ("Selin", ["Selin"]),
    ("Tove", ["Tove"]), ("Wren", ["Wren"]), ("Zed", ["Zed"]),
    ("Dara", ["Dara"]), ("Edo", ["Edo"]), ("Faro", ["Faro"]), ("Jala", ["Jala"]),
    ("Koa", ["Koa"]), ("Lior", ["Lior"]), ("Ori", ["Ori"]), ("Teo", ["Teo"]),
    # Documented cases and credited authors.
    ("Aadhaar", ["Aadhaar"]),
    ("ADM Jabalpur", ["ADM Jabalpur", "Jabalpur"]),
    ("Anderson, Elizabeth", ["Anderson"]),
    ("Grootboom", ["Grootboom", "Wallacedene"]),
    ("Hussainara Khatoon", ["Hussainara"]),
    ("Kesavananda Bharati", ["Kesavananda"]),
    ("Kumari, Santoshi", ["Santoshi"]),
    ("Nissenbaum, Helen", ["Nissenbaum"]),
    ("Ostrom, Elinor", ["Ostrom"]),
    ("Pettit, Philip", ["Pettit"]),
    ("Robodebt", ["Robodebt"]),
    ("Sen, Amartya", ["Amartya Sen", "Sen's"]),
    ("Shue, Henry", ["Shue"]),
    ("SyRI", ["SyRI"]),
    ("Urgenda", ["Urgenda"]),
]


def places() -> list[tuple[str, str]]:
    """The reading inputs the index covers, with how an entry names each."""
    manifest = json.loads((BOOK / "contents.json").read_text(encoding="utf-8"))
    rows = [(name, "opening") for name in manifest["front"] if name != "epigraph.md"]
    for index, part in enumerate(manifest["parts"], 1):
        opener = part.get("opener", {})
        roman = ["I", "II", "III", "IV", "V"][index - 1]
        if opener.get("status") == "landed":
            rows.append((opener["file"], f"Part {roman} case"))
        rows += [(c["file"], str(c["number"])) for c in part["chapters"] if c["status"] == "landed"]
    rows += [("method.md", "method")]
    return rows


def plain_title(name: str) -> str:
    """A reading input's title, lower-cased."""
    for line in (BOOK / name).read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip().lower()
    return ""


def plain(text: str) -> str:
    """The prose a reader meets: no comments, code, link targets or note definitions."""
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    text = re.sub(r"^\[\^[^\]]+\]:.*(?:\n(?:    .*|))*", "", text, flags=re.M)
    text = re.sub(r"```.*?```", " ", text, flags=re.S)
    text = re.sub(r"\]\([^)]*\)", "]", text)
    return " ".join(re.sub(r"[*_`]", "", text).split())


MOST = 8


def count(pattern: str, text: str) -> int:
    """Occurrences; a capitalised pattern is a name and keeps its capitals."""
    if pattern.startswith("re:"):
        return len(re.findall(r"(?<![\w-])" + pattern[3:] + r"(?![\w-])", text))
    flags = 0 if pattern[:1].isupper() else re.I
    return len(re.findall(r"(?<![\w-])" + re.escape(pattern) + r"(?![\w-])", text, flags))


def entries() -> list[tuple[str, list[str]]]:
    texts = [(label, plain((BOOK / name).read_text(encoding="utf-8"))) for name, label in places()]
    order = {label: index for index, (label, _) in enumerate(texts)}
    titled = {label: plain_title(name) for name, label in places()}
    found = []
    for term, patterns in TERMS:
        counts = {label: sum(count(p, text) for p in patterns) for label, text in texts}
        where = [label for label, n in counts.items() if n]
        if len(where) > MOST:
            principal = sorted((label for label in where if counts[label] > 1),
                               key=lambda label: (-counts[label], order[label]))[:MOST]
            # A chapter titled by the term is always one of its places.
            principal += [label for label in where if label not in principal
                          and term.lower() in titled[label]]
            where = sorted(principal, key=order.get)
        if where:
            found.append((term, where))
    return sorted(found, key=lambda item: item[0].lower().lstrip("'"))


def render() -> str:
    lines = [BEGIN, "## Index", "",
             "The principal places for each term, body, person and documented case.",
             "Numbers are chapters; *opening* is the opening note, *Part I case* and the",
             "like are the documented cases that open the Parts, and *method* is the",
             "optional method. A common term lists the chapters that use it most.",
             ""]
    letter = None
    for term, where in entries():
        initial = term[0].upper()
        if initial != letter:
            lines += ([""] if letter else []) + [f"### {initial}", ""]
            letter = initial
        lines.append(f"- {term}: {', '.join(where)}")
    lines += ["", END]
    return "\n".join(lines) + "\n"


def replace(text: str) -> str:
    region = render()
    if BEGIN in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        return text[:start] + region.rstrip("\n") + text[end:]
    return text.rstrip("\n") + "\n\n" + region


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the index is out of date")
    args = parser.parse_args()
    current = TARGET.read_text(encoding="utf-8")
    updated = replace(current)
    if args.check:
        if updated != current:
            print("the index in book-1/reference.md is out of date; run tools/book_index.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(updated, encoding="utf-8")
    print(f"Indexed {len(entries())} entries in {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
