#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Collect what would change each choice, and who bears its cost.

Every derived chapter's argument section closes with the evidence that would
make its author reconsider the choice, and says who bears the choice's cost.
This gathers both from the chapters, quoted, into two indexes: the conditions
grouped by the kind of evidence they name, and the costs grouped by who bears
them. `book-1/source/reconsider-source.json` assigns each quoted sentence its
kinds or bearers. The sentences are read from the chapters, so an edited
chapter moves its entries with it; a sentence with no assignment, or an
assignment whose sentence has gone, fails.

- The closing conditions are read from the last paragraph of the argument
  section that states one: from its first sentence saying what the author
  would reconsider, reopen, add, narrow, redraw or move toward, to the end of
  that paragraph. A derived chapter whose argument states none fails.
- Costs are read where each chapter keeps its account: its argument section,
  and a derived section on what its rules cost. An argument that cites costs
  "counted above" must have that section, and at least one of its costs must
  be quoted from it.

It writes `ui/reconsider.json`, which the companion shows quoted at
`reconsider/`, and a region of `book-1/reference.md` that lists, for each kind
of evidence and each group of people, the chapters whose arguments name it.
The book lists chapters rather than quoting, because its back matter counts
against the rule that the book stays majority-derived.

    python3 tools/reconsider_index.py           write both
    python3 tools/reconsider_index.py --check   fail unless both are current
    --root DIR                                  read and write under DIR instead

No dependencies, so the companion's tests can import it.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Paths within the repository, or within the root `--root` names.
MANIFEST = Path("book-1/contents.json")
SOURCE = Path("book-1/source/reconsider-source.json")
OUTPUT = Path("ui/reconsider.json")
REFERENCE = Path("book-1/reference.md")
BEGIN = "<!-- reconsider:begin; generated by tools/reconsider_index.py -->"
END = "<!-- reconsider:end -->"
# The region follows the map of choices and their arguments.
AFTER = "### Where a decision belongs\n"
COMPANION = "https://dhilipsiva.dev/rights-nobody-has-to-earn/reconsider/"
ARGUMENT = "## Argument:"
CONDITION = re.compile(r"\bI would (reconsider|reopen|move toward|add|narrow|redraw)\b")
COST_SECTION = re.compile(r"^(What (it|the \w+) costs?|Who bears the cost)$")
COUNTED = "counted above"
# Abbreviations after which a full stop ends no sentence.
ABBREVIATIONS = ("v.", "e.g.", "i.e.", "cf.", "No.")


def plain(markdown: str) -> str:
    """Markdown to plain text for a quotation: links keep their words, and
    emphasis, inline code, note references and comments are removed."""
    text = re.sub(r"<!--.*?-->", "", markdown, flags=re.S)
    text = re.sub(r"\[\^[^\]]+\]", "", text)
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    return " ".join(text.split())


def sentences(paragraph: str) -> list[str]:
    pieces = re.split(r"(?<=[.?!])\s+(?=[A-Z“\"(])", paragraph)
    joined: list[str] = []
    for piece in pieces:
        if joined and joined[-1].endswith(ABBREVIATIONS):
            joined[-1] += " " + piece
        else:
            joined.append(piece)
    return joined


def slug(text: str) -> str:
    """The heading fragments the book builder and the reader give a heading."""
    return re.sub(r"[^\w\- ]", "", text.lower()).replace(" ", "-")


def sections(text: str) -> list[tuple[str, str]]:
    """Each `## ` section of a chapter as (heading, body)."""
    parts = re.split(r"^## (.+)$", re.sub(r"<!--.*?-->", "", text, flags=re.S), flags=re.M)
    return [(parts[i].strip(), parts[i + 1]) for i in range(1, len(parts), 2)]


def paragraphs(body: str) -> list[str]:
    """Prose paragraphs, without note definitions, lists or tables."""
    kept = []
    for block in re.split(r"\n\s*\n", body.strip()):
        block = block.strip()
        if not block or block.startswith(("[^", "|", "- ", "* ", "#")):
            continue
        kept.append(plain(block))
    return kept


def derived_chapters(manifest: dict) -> list[dict]:
    return [c for part in manifest["parts"] for c in part["chapters"]
            if c.get("role") == "derived" and c.get("status") == "landed"]


def read_chapter(chapter: dict, root: Path = ROOT) -> dict:
    """A chapter's argument section, closing conditions and cost-bearing text."""
    text = (root / "book-1" / chapter["file"]).read_text(encoding="utf-8")
    number = chapter["number"]
    found = sections(text)
    argued = [(h, b) for h, b in found if ("## " + h).startswith(ARGUMENT)]
    if len(argued) != 1:
        raise ValueError(f"Chapter {number} has no argument section")
    heading, body = argued[0]
    prose = paragraphs(body)
    closing = [p for p in prose if CONDITION.search(p)]
    if not closing:
        raise ValueError(f"Chapter {number}'s argument states no condition that would change its choice")
    last = sentences(closing[-1])
    first = next(i for i, s in enumerate(last) if CONDITION.search(s))
    costs = [(heading, p) for p in prose]
    counted = COUNTED in " ".join(prose)
    cost_sections = [h for h, _ in found if COST_SECTION.match(h)]
    if counted and not cost_sections:
        raise ValueError(f"Chapter {number}'s argument cites costs counted above, and no section counts them")
    for h, b in found:
        if h in cost_sections:
            costs += [(h, p) for p in paragraphs(b)]
    return {
        "number": number,
        "title": chapter["title"],
        "file": chapter["file"],
        "argument": heading,
        "conditions": last[first:],
        "costs": [(h, s) for h, p in costs for s in sentences(p)],
        "counted": counted,
        "cost_sections": cost_sections,
    }


def matching(needle: str, candidates: list[str]) -> list[int]:
    return [i for i, s in enumerate(candidates) if needle in s]


def build(manifest: dict | None = None, source: dict | None = None, root: Path = ROOT) -> dict:
    manifest = manifest if manifest is not None else json.loads((root / MANIFEST).read_text(encoding="utf-8"))
    source = source if source is not None else json.loads((root / SOURCE).read_text(encoding="utf-8"))
    kinds = {k["id"]: k for k in source["kinds"]}
    bearers = {b["id"]: b for b in source["bearers"]}
    conditions: dict[str, list[dict]] = {k: [] for k in kinds}
    costs: dict[str, list[dict]] = {b: [] for b in bearers}
    problems: list[str] = []
    chapters = derived_chapters(manifest)
    assigned = source["chapters"]
    for extra in sorted(set(assigned) - {str(c["number"]) for c in chapters}, key=int):
        problems.append(f"Chapter {extra} is assigned but is no derived chapter")
    for chapter in chapters:
        read = read_chapter(chapter, root)
        number = read["number"]
        entry = assigned.get(str(number), {})
        place = {"chapter": number, "title": read["title"], "file": f"book-1/{read['file']}"}
        # Conditions: every sentence of the closing conditions is assigned
        # kinds, or continues the sentence before it.
        statements: list[tuple[str, list[str]]] = []
        used = set()
        for sentence in read["conditions"]:
            hits = [i for i, a in enumerate(entry.get("conditions", [])) if a["needle"] in sentence]
            if len(hits) != 1:
                problems.append(f"Chapter {number}: {len(hits)} assignments for the condition “{sentence}”")
                continue
            used.add(hits[0])
            assignment = entry["conditions"][hits[0]]
            if assignment.get("continues"):
                if not statements:
                    problems.append(f"Chapter {number}: the first condition cannot continue another")
                    continue
                statements[-1] = (statements[-1][0] + " " + sentence, statements[-1][1])
            else:
                unknown = [k for k in assignment.get("kinds", []) if k not in kinds]
                if not assignment.get("kinds") or unknown:
                    problems.append(f"Chapter {number}: the condition “{sentence}” has no known kind")
                    continue
                statements.append((sentence, assignment["kinds"]))
        for i, assignment in enumerate(entry.get("conditions", [])):
            if i not in used:
                problems.append(f"Chapter {number}: no closing condition contains “{assignment['needle']}”")
        for text, names in statements:
            for name in names:
                conditions[name].append({**place, "heading": read["argument"], "text": text})
        # Costs: each assignment quotes the one sentence of the chapter's
        # cost-bearing text that contains its needle.
        quoted = 0
        from_section = 0
        candidates = [s for _, s in read["costs"]]
        for assignment in entry.get("costs", []):
            hits = matching(assignment["needle"], candidates)
            if len(hits) != 1:
                problems.append(f"Chapter {number}: the cost “{assignment['needle']}” occurs {len(hits)} times")
                continue
            heading, sentence = read["costs"][hits[0]]
            unknown = [b for b in assignment.get("bearers", []) if b not in bearers]
            if not assignment.get("bearers") or unknown:
                problems.append(f"Chapter {number}: the cost “{assignment['needle']}” has no known bearer")
                continue
            quoted += 1
            from_section += heading in read["cost_sections"]
            for name in assignment["bearers"]:
                costs[name].append({**place, "heading": heading, "text": sentence})
        if not quoted:
            problems.append(f"Chapter {number}: no cost is quoted")
        if read["counted"] and not from_section:
            problems.append(f"Chapter {number}: its costs are counted in {read['cost_sections']}, and none is quoted from there")
    for name, entries in list(conditions.items()) + list(costs.items()):
        if not entries:
            problems.append(f"nothing is listed under {name}")
    if problems:
        raise ValueError("\n".join(problems))
    return {
        "license": "CC-BY-4.0",
        "generated_by": "tools/reconsider_index.py",
        "title": source["title"],
        "note": source["note"],
        "conditions": [{"id": k, "title": kinds[k]["title"], "entries": conditions[k]} for k in kinds],
        "costs": [{"id": b, "title": bearers[b]["title"], "entries": costs[b]} for b in bearers],
    }


def render(document: dict) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def chapter_links(entries: list[dict]) -> str:
    seen: dict[int, str] = {}
    for entry in entries:
        name = Path(entry["file"]).name
        seen.setdefault(entry["chapter"], f"[{entry['chapter']}]({name}#{slug(entry['heading'])})")
    return ", ".join(seen[n] for n in sorted(seen))


def wrap(text: str, indent: str = "") -> list[str]:
    """Lines of at most 80 columns, breaking only between words."""
    lines = textwrap.wrap(text, width=80, subsequent_indent=indent,
                          break_long_words=False, break_on_hyphens=False)
    return lines or [""]


def region(document: dict, intro: str) -> str:
    lines = [BEGIN, f"### {document['title']}", ""] + wrap(intro) + ["", "What would change a choice:", ""]
    for group in document["conditions"]:
        lines += wrap(f"- **{group['title']}:** {chapter_links(group['entries'])}", "  ")
    lines += ["", "Who bears the costs:", ""]
    for group in document["costs"]:
        lines += wrap(f"- **{group['title']}:** {chapter_links(group['entries'])}", "  ")
    lines += ["", END]
    return "\n".join(lines)


def updated_reference(text: str, document: dict, intro: str) -> str:
    block = region(document, intro)
    if BEGIN in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        return text[:start] + block + text[end:]
    if AFTER not in text:
        raise ValueError(f"reference.md has no {AFTER.strip()!r} to place the region before")
    at = text.index(AFTER)
    return text[:at] + block + "\n\n" + text[at:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="fail unless ui/reconsider.json and the reference region are current")
    parser.add_argument("--root", type=Path, default=ROOT,
                        help="read and write under this directory instead of the repository")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    source = json.loads((root / SOURCE).read_text(encoding="utf-8"))
    try:
        document = build(source=source, root=root)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    fresh = render(document)
    output, target = root / OUTPUT, root / REFERENCE
    reference = target.read_text(encoding="utf-8")
    fresh_reference = updated_reference(reference, document, source["book_intro"])
    if args.check:
        stale = []
        if not output.exists() or output.read_text(encoding="utf-8") != fresh:
            stale.append(OUTPUT.as_posix())
        if reference != fresh_reference:
            stale.append(REFERENCE.as_posix())
        if stale:
            print(f"{' and '.join(stale)} stale; run python3 tools/reconsider_index.py", file=sys.stderr)
            return 1
        print("ui/reconsider.json and the reference region are current")
        return 0
    output.write_text(fresh, encoding="utf-8")
    target.write_text(fresh_reference, encoding="utf-8")
    conditions = sum(len(g["entries"]) for g in document["conditions"])
    costs = sum(len(g["entries"]) for g in document["costs"])
    print(f"wrote ui/reconsider.json and the reference region: {conditions} condition entries, "
          f"{costs} cost entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
